-- H2 兼容 schema for Repository tests
-- 前置: predecessor_ids 改 VARCHAR(64) 存 JSON 字符串 (PG 是 bigint[])
-- 前置: hourly_rate 升级到 V4.0 字段 (user_id / end_month / role_code / effective_month / remark / created_by)
-- 前置: 新增 role_cost_default 表 (P0-A.1)

DROP TABLE IF EXISTS wbs_assignment;
DROP TABLE IF EXISTS wbs_task;
DROP TABLE IF EXISTS budget_line;
DROP TABLE IF EXISTS budget_snapshot;
DROP TABLE IF EXISTS hourly_rate_v4;
DROP TABLE IF EXISTS role_cost_default;
DROP TABLE IF EXISTS milestone;
DROP TABLE IF EXISTS milestone_phase;
DROP TABLE IF EXISTS app_user;
DROP TABLE IF EXISTS project;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(256),
    full_name VARCHAR(64),
    display_name VARCHAR(128),
    email VARCHAR(128),
    phone VARCHAR(32),
    role VARCHAR(32),
    department_id BIGINT,
    primary_role_id BIGINT,
    job_title VARCHAR(64),
    default_hourly_rate NUMERIC(10,2) DEFAULT 0,
    login_fail_count INT NOT NULL DEFAULT 0,
    dingtalk_user_id VARCHAR(64),
    backup_user_id BIGINT,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    customer VARCHAR(256),
    description TEXT,
    type_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    health_id BIGINT,
    department_id BIGINT,
    pm_user_id BIGINT,
    plan_start_date DATE,
    plan_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    progress_pct INT NOT NULL DEFAULT 0,
    baseline_version INT NOT NULL DEFAULT 0,
    bu_id BIGINT,
    pl_id BIGINT,
    rp_id BIGINT,
    closed_at TIMESTAMP WITH TIME ZONE,
    created_by BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS project_type (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(64) NOT NULL);
CREATE TABLE IF NOT EXISTS project_status (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(64) NOT NULL, is_terminal BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE IF NOT EXISTS health_level (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(32) NOT NULL UNIQUE, name VARCHAR(64) NOT NULL);

CREATE TABLE IF NOT EXISTS wbs_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    parent_id BIGINT,
    wbs_code VARCHAR(32) NOT NULL,
    name VARCHAR(256) NOT NULL,
    task_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    owner_user_id BIGINT,
    plan_start_date DATE,
    plan_end_date DATE,
    actual_start_date DATE,
    actual_end_date DATE,
    plan_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
    actual_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
    progress_pct INT NOT NULL DEFAULT 0,
    weight INT NOT NULL DEFAULT 1,
    is_critical BOOLEAN NOT NULL DEFAULT FALSE,
    is_milestone BOOLEAN NOT NULL DEFAULT FALSE,
    milestone_id BIGINT,
    predecessor_ids VARCHAR(64),
    deliverable TEXT,
    remark TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_wbs_task_project_code UNIQUE (project_id, wbs_code)
);

CREATE TABLE IF NOT EXISTS wbs_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wbs_task_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(64) NOT NULL DEFAULT 'DOER',
    planned_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
    actual_hours NUMERIC(10,2) NOT NULL DEFAULT 0,
    start_date DATE,
    end_date DATE,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_wbs_assignment_task_user UNIQUE (wbs_task_id, user_id)
);

CREATE TABLE IF NOT EXISTS budget_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    wbs_task_id BIGINT,
    category VARCHAR(32) NOT NULL,
    name VARCHAR(128) NOT NULL,
    planned_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    committed_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    actual_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    created_by BIGINT,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_budget_line_project_category UNIQUE (project_id, category)
);

CREATE TABLE IF NOT EXISTS budget_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    version INT NOT NULL DEFAULT 1,
    reason VARCHAR(256),
    bac NUMERIC(14,2) NOT NULL DEFAULT 0,
    pv NUMERIC(14,2) NOT NULL DEFAULT 0,
    ev NUMERIC(14,2) NOT NULL DEFAULT 0,
    ac NUMERIC(14,2) NOT NULL DEFAULT 0,
    cpi NUMERIC(6,3) NOT NULL DEFAULT 1,
    spi NUMERIC(6,3) NOT NULL DEFAULT 1,
    eac NUMERIC(14,2) NOT NULL DEFAULT 0,
    etc NUMERIC(14,2) NOT NULL DEFAULT 0,
    vac NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- P0-A.1 V4.0 hourly_rate
CREATE TABLE IF NOT EXISTS hourly_rate_v4 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(32) NOT NULL,
    user_id BIGINT,
    rate NUMERIC(10,2) NOT NULL,
    effective_month DATE NOT NULL,
    end_month DATE,
    remark VARCHAR(256),
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_hourly_rate_v4_user_month ON hourly_rate_v4 (user_id, effective_month);
CREATE INDEX idx_hourly_rate_v4_role_month ON hourly_rate_v4 (role_code, effective_month);

-- P0-A.1 V4.0 role_cost_default
CREATE TABLE IF NOT EXISTS role_cost_default (
    code VARCHAR(32) PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    rate NUMERIC(10,2) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);

-- Milestone + MilestonePhase (V3.1 引入阶段; Milestone.phase_id NOT NULL)
CREATE TABLE IF NOT EXISTS milestone_phase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    phase_id BIGINT NOT NULL,
    sequence INT NOT NULL DEFAULT 0,
    name VARCHAR(256) NOT NULL,
    status_id BIGINT,
    owner_user_id BIGINT,
    plan_date DATE,
    actual_date DATE,
    completed_at TIMESTAMP WITH TIME ZONE,
    weight INT NOT NULL DEFAULT 1,
    deliverable TEXT,
    remark TEXT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_milestone_phase FOREIGN KEY (phase_id) REFERENCES milestone_phase(id),
    CONSTRAINT uk_milestone_proj_phase_seq UNIQUE (project_id, phase_id, sequence)
);

CREATE INDEX idx_milestone_phase ON milestone(phase_id);

-- ============================================================
-- role + department + seed (workload / timesheet 测试 seed 依赖)
-- ============================================================

DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS department;

CREATE TABLE IF NOT EXISTS department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64),
    name VARCHAR(128) NOT NULL,
    parent_id BIGINT,
    leader_user_id BIGINT,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(256),
    built_in BOOLEAN NOT NULL DEFAULT TRUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO role (id, code, name, description, built_in, enabled, sort_order) VALUES
    (1, 'PM', '项目经理', '', TRUE, TRUE, 10),
    (2, 'VIEWER', '只读', '', TRUE, TRUE, 100),
    (3, 'PMO_ADMIN', 'PMO管理员', '', TRUE, TRUE, 5),
    (4, 'DEPT_LEAD', '部门负责人', '', TRUE, TRUE, 15),
    (5, 'EXEC', '高管', '', TRUE, TRUE, 1),
    (6, 'TEST', '测试工程师', '', TRUE, TRUE, 30),
    (7, 'DEV', '开发工程师', '', TRUE, TRUE, 20);
