-- ============================================================
-- V2.6 (H2 兼容版, 给 JPA 测试用) P4 风险表
-- ============================================================
DROP TABLE IF EXISTS risk_history;
DROP TABLE IF EXISTS risk_response;
DROP TABLE IF EXISTS risk;

CREATE TABLE risk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    code VARCHAR(32) NOT NULL,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    category VARCHAR(16) NOT NULL,
    probability INT NOT NULL,
    impact INT NOT NULL,
    score INT NOT NULL,
    level VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    owner_user_id BIGINT,
    mitigation TEXT,
    contingency TEXT,
    response_strategy VARCHAR(16),
    identified_date DATE NOT NULL DEFAULT CURRENT_DATE,
    target_close_date DATE,
    actual_close_date DATE,
    related_wbs_task_id BIGINT,
    related_milestone_id BIGINT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_risk_project_code UNIQUE (project_id, code)
);

CREATE TABLE risk_response (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id BIGINT NOT NULL,
    action VARCHAR(256) NOT NULL,
    owner_user_id BIGINT,
    due_date DATE,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(16) NOT NULL DEFAULT 'PLANNED',
    note TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE risk_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    field_name VARCHAR(64),
    old_value TEXT,
    new_value TEXT,
    comment TEXT,
    operator_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
